import type { Metadata } from "next";
import { Instrument_Sans } from "next/font/google";
import { Toaster } from "sonner";
import "./globals.css";
import { RecentlyViewedProvider } from "./context/RecentlyViewedContext";

// Main font
const instrumentSans = Instrument_Sans({
  variable: "--font-instrument-sans",
  subsets: ["latin"],
  weight: ["400", "600"],
});

export const metadata: Metadata = {
  title: "Afro Connect | finding braiding solutions",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body className={`${instrumentSans.variable} font-sans antialiased flex flex-col min-h-screen`}>
        <RecentlyViewedProvider>
          <main className="flex-1">{children}</main>
          <Toaster position="bottom-right" richColors />
        </RecentlyViewedProvider>
      </body>
    </html>
  );
}
